development:
  libraries:
    - path: googletest
    - path: simdpp
    - path: flathashmap
    - path: nanorange
    - path: taskflow
    - path: nlohmannjson
    - path: glm
    - path: fmt
    - path: spdlog