development:
  libraries:
    - name: Zefiros-Software/nlohmannjson
      version: master
      definition: ./
      repository: https://github.com/nlohmann/json.git

extract:
  includes:
    - "include/**/*.hpp"

build:
  template: headeronly
  includes:
    - include
  features:
    - cxx_std_11
