development:
  libraries:
    - name: Zefiros-Software/nanorange
      version: master
      definition: ./
      repository: https://github.com/tcbrindle/NanoRange.git

extract:
  includes:
    - "single_include/*.hpp"
build:
  template: headeronly
  includes:
    - single_include
  features:
    - cxx_std_17
  custom:
    - |
      if (MSVC)
      target_compile_options("${PROJECT_NAME}" INTERFACE /permissive-)
      endif()