development:
  libraries:
    - name: Zefiros-Software/nanorange
      version: master
      definition: ./
      repository: https://github.com/tcbrindle/NanoRange.git

extract:
  include:
    - "single_include/*.hpp"
build:
  template: headeronly
  include:
    - single_include
  feature:
    - cxx_std_17
  custom: |
      if (MSVC)
      target_compile_options("${PROJECT_NAME}" INTERFACE /permissive-)
      endif()

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/nanorange