development:
  libraries:
    - name: Zefiros-Software/GoogleTest:gtest
      version: master
      definition: ./

extract:
  include:
    - "googletest/include/**/*.h"
    - "googletest/src/**.cc"
    - "googletest/src/**.h"
build:
  template: library
  source:
    - googletest/src/gtest-all.cc
  include:
    - googletest/include
  private:
    include: 
      - googletest
      
  custom: |
      find_package(Threads REQUIRED)
      target_link_libraries("${PROJECT_NAME}" Threads::Threads)


  self:
    template: library-test
    source:
      - "test/*.cpp"
    private:
      link:
        - Zefiros-Software/GoogleTest:gtest
