development:
  libraries:
    - name: Zefiros-Software/taskflow
      version: master
      definition: ./
      repository: https://github.com/cpp-taskflow/cpp-taskflow.git

extract:
  includes:
    - "taskflow/**/*.hpp"
build:
  template: headeronly
  includes:
    - ./
  features:
    - cxx_std_17

  custom:
    - |
      if(UNIX)
      target_link_libraries("${PROJECT_NAME}" INTERFACE pthread)
      endif()