development:
  libraries:
    - name: Zefiros-Software/taskflow
      version: master
      definition: ./
      repository: https://github.com/cpp-taskflow/cpp-taskflow.git

extract:
  include:
    - "taskflow/**/*.hpp"
build:
  template: headeronly
  include:
    - ./
  feature:
    - cxx_std_17
  conditions:
    - on: UNIX
      let:
        link:
          - Threads::Threads

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/taskflow
