development:
  libraries:
    - name: Zefiros-Software/simdpp
      version: master
      definition: ./
      repository: https://github.com/p12tic/libsimdpp.git

extract:
  include:
    - "simdpp/**/*.h"
    - "simdpp/**/*.hpp"
    - "simdpp/**/*.inl"
build:
  template: headeronly
  include:
    - ./
  feature:
    - cxx_std_11

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/simdpp
