development:
  libraries:
    - name: Zefiros-Software/fmt
      version: '^5.0.0'
      definition: ./
      repository: https://github.com/fmtlib/fmt.git

extract:
  include:
    - "include/**"
    - "src/**.cc"
build:
  template: library
  source:
    - src/*.cc
  include:
    - include
  feature:
    - cxx_std_14

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/fmt