development:
  libraries:
    - name: Zefiros-Software/boost
      version: '^1.70.0'
      definition: ./
      repository: https://github.com/boostorg/boost.git
      settings:
        modules:
          - atomic
requires: 
  extractor:
    path: extract

build:
  template: library
  source:
    - "libs/*/src/**"
    - "!libs/*/src/pthread/**"
    - "!libs/*/src/win32/**"
  include:
    - ./
  define: 
    - "BOOST_ALL_NO_LIB" 
    - "BOOST_TEST_NO_MAIN"
  feature:
    - cxx_std_11
  private:
    conditions:
      - on: MSVC
        let:
          source: 
            - "libs/*/src/win32/**"
      - on: NOT MSVC
        let:
          source: 
            - "libs/*/src/pthread/**"
          custom: |
            
            find_package(Threads REQUIRED)
            target_link_libraries("${PROJECT_NAME}" Threads::Threads)

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/boost
