development:
  libraries:
    - name: Zefiros-Software/boost
      version: '^1.70.0'
      definition: ./
      repository: https://github.com/boostorg/boost.git
      settings:
        modules:
          - atomic
requires: 
  extractor:
    path: extract

build:
  template: library
  source:
    - "libs/*/src/**"
    - "!libs/*/src/pthread/**"
    - "!libs/*/src/win32/**"
  include:
    - ./
  define: 
    - "BOOST_ALL_NO_LIB" 
    - "BOOST_TEST_NO_MAIN"
  feature:
    - cxx_std_11
  globs:
    pthread: 
      - "libs/*/src/pthread/**"
    win32: 
      - "libs/*/src/win32/**"
  custom: |
      if (MSVC)

      target_sources("${PROJECT_NAME}" PRIVATE 
        {{#each globs.win32}}
        {{this}}
        {{/each}}
      )

      else()
      
      find_package(Threads REQUIRED)
      target_sources("${PROJECT_NAME}" PRIVATE
        {{#each globs.pthread}}
        {{this}}
        {{/each}}
      )

      target_link_libraries("${PROJECT_NAME}" Threads::Threads)
      
      endif()


  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/boost
