development:
  libraries:
    - name: Zefiros-Software/flathashmap
      version: master
      definition: ./
      repository: https://github.com/skarupke/flat_hash_map.git

extract:
  includes:
    - "*.hpp"
build:
  template: headeronly
  includes:
    - ./
  features:
    - cxx_std_11
