development:
  libraries:
    - name: Zefiros-Software/flathashmap
      version: master
      definition: ./
      repository: https://github.com/skarupke/flat_hash_map.git

extract:
  include:
    - "*.hpp"
build:
  template: headeronly
  include:
    - ./
  feature:
    - cxx_std_11

  self:
    template: library-test
    source:
      - "test/**.cpp"
    private:
      link:
        - Zefiros-Software/flathashmap
